# Generated by Django 3.2.4 on 2021-06-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resenna',
            fields=[
                ('idResenna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Reseña')),
                ('tipoResenna', models.CharField(max_length=15, verbose_name='Tipo de reseña')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreC', models.CharField(max_length=40, verbose_name='Nombre completo cliente')),
                ('comentario', models.CharField(max_length=150, verbose_name='comentario')),
                ('resenna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPanda.resenna')),
            ],
        ),
    ]
