# Generated by Django 3.2.4 on 2021-06-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPanda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarioc',
            name='id',
        ),
        migrations.AlterField(
            model_name='comentarioc',
            name='NombreC',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Nombre completo cliente'),
        ),
    ]
